org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

mod_id=concerto
mod_name=Concerto
mod_license=GPL-v3 & more
mod_version=1.6.1
mod_group_id=top.gregtao
mod_authors=GregTao, commonplace(KSmc_brigade)
mod_description=Concerto
archives_base_name=Concerto