subprojects {
    project.archives_base_name = mod_name + "-forge"

    dependencies {
        my (project(":core")) {
            exclude group: 'org.slf4j', module: 'slf4j-api'
            exclude group: 'com.google.code.gson', module: 'gson'
            exclude group: 'org.jetbrains', module: 'annotations'
        }
    }

    configurations.configureEach {
        resolutionStrategy {
            force 'net.sf.jopt-simple:jopt-simple:5.0.4'
        }
    }

    shadowJar {

        configurations = [project.configurations.my]
        dependencies {
            exclude(dependency('junit:junit'))
        }

        relocationPrefix = 'top.gregtao.concerto.libs'
        enableRelocation = true

        relocate 'top.gregtao.concerto.core', 'top.gregtao.concerto.core'
        relocate 'top.gregtao.concerto.services', 'top.gregtao.concerto.services'

        exclude 'META-INF/maven/**'
        //exclude 'META-INF/versions/**/*'

        from(rootProject.file("LICENSE")) {
            rename {"LICENSE_${project.archives_base_name}"}
            into("META-INF")
        }

        mergeServiceFiles()
    }

    assemble.dependsOn shadowJar
}